
<h1>numpy.testing.assert_raises_regex<a class="headerlink" href="#numpy-testing-assert-raises-regex" title="Permalink to this heading">#</a></h1>
<dl class="py function">
<dt class="sig sig-object py" id="numpy.testing.assert_raises_regex">
<span class="sig-prename descclassname"><span class="pre">testing.</span></span><span class="sig-name descname"><span class="pre">assert_raises_regex</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">exception_class</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">expected_regexp</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">callable</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">*args</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">**kwargs)</span> <span class="pre">assert_raises_regex(exception_class</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">expected_regexp</span></span></em><span class="sig-paren">)</span><a class="reference external" href="https://github.com/numpy/numpy/blob/v1.24.0/numpy/testing/_private/utils.py#L1384-L1402"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#numpy.testing.assert_raises_regex" title="Permalink to this definition">#</a></dt>
<dd><p>Fail unless an exception of class exception_class and with message that
matches expected_regexp is thrown by callable when invoked with arguments
args and keyword arguments kwargs.</p>
<p>Alternatively, can be used as a context manager like <a class="reference internal" href="numpy.testing.assert_raises.html#numpy.testing.assert_raises" title="numpy.testing.assert_raises"><code class="xref py py-obj docutils literal notranslate"><span class="pre">assert_raises</span></code></a>.</p>
<p class="rubric">Notes</p>
<div class="versionadded">
<p><span class="versionmodified added">New in version 1.9.0.</span></p>
</div>
</dd></dl>

